linters:
  disable:
    - gosec
    - noctx
    - errorlint
    - exhaustive
    - scopelint
    - rowserrcheck
    - sqlclosecheck
    - maligned
  presets:
    - bugs
    # - comment
    # - complexity
    # - error
    - format
    - import
    # - metalinter
    # - module
    - performance
    # - sql
    # - style
    # - test
    # - unused
